version: '3'
services:
  favor_admin:
    build: .
    volumes:
      - ~/.ssh/:/root/.ssh
      - .dockervenv:/src/.venv
      - .:/src
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: '/src/admin-cred.json'
      FIRESTORE_EMULATOR_HOST: 'host.docker.internal:8080'
      FIREBASE_AUTH_EMULATOR_HOST: 'host.docker.internal:9099'
      GCLOUD_PROJECT: 'dev-favor'
    ports:
      - 8001:8001
