version: '3'
services:
  demo-app:
    build: .
    volumes:
      - ~/.ssh/:/root/.ssh
      - .dockervenv:/src/.venv
      - .:/src
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: '/src/admin-cred.json'
    ports:
      - 8000:8000
